### ISSUE TITLE
NameError: name 'JsonConfig' is not defined

### ISSUE THREAD

**Issue by fakhrirobi** [GibbsConsulting/django-plotly-dash#423] opened 2022-11-05 16:10 UTC
![image](https://user-images.githubusercontent.com/60530014/200129295-382c9877-cfff-4723-98d1-75d30b738c78.png)

**Comment by fakhrirobi** [comment] 2022-11-05 16:11
![image](https://user-images.githubusercontent.com/60530014/200129321-386b707f-882f-4935-97eb-74706542ce34.png)

**Comment by delsim** [comment] 2022-11-05 23:29
This looks like a duplicate of #421

The fix is to make the code work with the orjson package. Until this is done, as a workaround, can you remove this package?

**Comment by fakhrirobi** [comment] 2022-11-06 02:54
for the temporary  uninstalling orjson may be a solution

**Closed** 2022-11-06 02:55 UTC
