### ISSUE TITLE
min.js.map MIME type not executable

### ISSUE THREAD

**Issue by OmenApps** [GibbsConsulting/django-plotly-dash#86] opened 2018-12-24 16:22 UTC
As reported on the dash github under [issue #488](https://github.com/plotly/dash/issues/488):

When trying to use a plotly app in django_plotly_dash, I (and other folks) get both of the following:

> Refused to execute script from 'https://unpkg.com/dash-core-components@0.41.0/dash_core_components/dash_core_components.min.js.map' because its MIME type ('application/json') is not executable, and strict MIME type checking is enabled.
> 127.0.0.1/:1 
> 
> Refused to execute script from 'https://unpkg.com/dash-renderer@0.16.1/dash_renderer/dash_renderer.min.js.map' because its MIME type ('application/json') is not executable, and strict MIME type checking is enabled.

My environment:
using

- plotly 3.4.2
- dash 0.35.0
- django 2.1.4
- django_plotly_dash 0.9.4
- python 3.7.1

@T4rk1n noted regarding django_plotly_dash:

> They handle the bundles differently and need to patch it to not auto serve the dist items marked as dynamic.

I think @MarcSkovMadsen and possibly @edwindt and @boludo00 would be interested in a solution as well.

**Comment by T4rk1n** [comment] 2018-12-25 00:42
You need to update the requirements of dash, dash-core-components, dash-html-components to the latest. Then when you open the dev console there should the message:
```
Refused to execute script from 'https://unpkg.com/dash-core-components@0.41.0/dash_core_components/dash_core_components.min.js.map' because its MIME type ('application/json') is not executable, and strict MIME type checking is enabled.
127.0.0.1/:1
```

We added a `dynamic` flag in the `_js_dist` of each package, you need to exclude those items from being automatically served on the index.

**Comment by delsim** [comment] 2018-12-27 02:55
When I run the demo after upgrading the dash packages, I observe these error messages in the console, but also that the apps continue to work correctly. Am I correct in thinking that the issue is the unwanted warning messages, or is there something else happening here?

For future reference, the package versions were:
```bash
(env) delsim:~/local/django-plotly-dash$ pip freeze | grep dash
dash==0.35.0
dash-core-components==0.41.0
dash-html-components==0.13.4
dash-renderer==0.16.1
```

**Comment by OmenApps** [comment] 2018-12-27 04:57
Well, I feel like a dummy. Turns out @delsim is correct. I had something misconfigured *and* saw the console message, then saw the new issue over at plotly, and thought this was the likely reason my charts weren't rendering properly.

In fact, the two errors are simply an annoying message, and not apparently contributing to any failure of charts to render.

**Comment by delsim** [comment] 2018-12-28 05:58
I'm going to mark this as closed; please reopen if needed.

**Comment by GibbsConsulting** [comment] 2018-12-28 05:59
I'm going to close this issue; please reopen if needed, particularly if the underlying dash fix doesn't get rid of the warning.

**Closed by GibbsConsulting** 2018-12-28 05:59 UTC
