### ISSUE TITLE
Initial migration fails with RuntimeError

### ISSUE THREAD

**Issue by chr15m** [GibbsConsulting/django-plotly-dash#281] opened 2020-10-06 08:58 UTC
I am installing `django_plotly_dash` into an existing application by following the instructions in the README and I get the following error when I try to run the `migrate` management command:

```
RuntimeError: Model class django_plotly_dash.models.StatelessApp doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
```

Any ideas on how I can drill down and figure out what is causing this? Thank you!

**Comment by GibbsConsulting** [comment] 2020-10-07 14:04
A quick google suggests that this is a less-than-helpful error message that should really read 'something is not configured correctly' and is probably due to something like a non-standard project structure, a stray `__init__.py` file, or using relative imports.

I googled for "Django doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS" and got multiple answers with this common theme.

**Comment by chr15m** [comment] 2020-10-07 14:05
Excellent, thanks for the pointer. Will investigate.

**Comment by GibbsConsulting** [comment] 2020-10-08 15:15
@chr15m hopefully finding the issue isn't too painful. I've had it myself in the past. As it is almost certainly something specific to your config, I'm closing this issue. If it does turn out to be something in the codebase, please either reopen or create a new issue with details.

**Closed by GibbsConsulting** 2020-10-08 15:15 UTC

**Comment by chr15m** [comment] 2020-10-13 02:28
In a truly face-palm moment, I discovered I had added the string `'django_plotly_dash.apps.DjangoPlotlyDashConfig'` to `MIDDLEWARE` instead of `INSTALLED_APPS` in `settings.py`, and that is what was causing the above error. tl;dr: PEBCAK.
